title: "From sudden to long term success: what's the secret?"
description: ADAngerously neat analysis to uncover the optimal strategies
theme: jekyll-theme-cayman
show_downloads: false
github_project: https://github.com/epfl-ada/ada-2022-project-adangerousteam
